10 KEY OFF : WIDTH 80 : SCREEN 0,0,0 : COLOR 7,0 : RESTORE : CLEAR : CLS
20 'ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
30 'บ                                                             บ
40 'บ            PROGRAM: HEADER FOR THE IBM PC.                  บ
50 'บ            CREATED BY:  John Doe (CoderDawg)                บ
60 'บ                        (C) 1981                             บ
80 'บ                                                             บ
70 'ฬอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
80 'บ                                                             บ
90 'บ                                                             บ